---
- hosts: all
  connection: local

  vars:
    device:
      ip_address: "{{ panos_url }}"
      username: "{{ panos_user }}"
      password: "{{ panos_password }}"

  tasks:
    - paloaltonetworks.panos.panos_zone:
        provider: '{{ device }}'
        zone: "{{ item.zone }}"
        mode: "{{ item.mode }}"
      loop:
        - zone: Untrust1
          mode: layer3
        - zone: Untrust2
          mode: layer3
        - zone: Trust1
          mode: layer3
        - zone: Trust2
          mode: layer3
        - zone: Trust3
          mode: layer3

    - paloaltonetworks.panos.panos_commit_firewall:
        provider: '{{ device }}'
