---
- hosts: all
  gather_facts: false
  vars:
    ansible_httpapi_use_ssl: yes
    ansible_httpapi_validate_certs: no
    ansible_httpapi_port: 443
  vars_files:
    - "{{ load_file_name }}"
  tasks:
    - fortinet.fortios.fortios_firewall_policy:
        vdom: root
        state: present
        firewall_policy:
          policyid: "{{ item.policy_num }}"
          name: "{{ item.policy_name }}"
          srcintf:
            - name: "{{ item.src_port }}"
          dstintf:
            - name: "{{ item.dest_port }}"
          srcaddr:
            - name: "{{ item.src_addr }}"
          dstaddr:
            - name: "{{ item.dest_addr}}"
          service: "{{ item.protocol }}"
          status: enable
          schedule: always
          action: "{{ item.access_ctrl }}"
          nat: enable
      loop: "{{ policies }}"
