---
- hosts: all
  connection: local

  vars:
    device:
      ip_address: "{{ panos_url }}"
      username: "{{ panos_user }}"
      password: "{{ panos_password }}"
  vars_files:
    - "{{ load_file_name }}"
  tasks:

    - paloaltonetworks.panos.panos_security_rule:
        provider: "{{ device }}"
        rule_name: Policy0
        description: ""
        source_zone:
          - Untrust1
        source_ip:
          - any
        destination_zone:
          - Trust1
        destination_ip:
          - any
        application:
          - ssh
        action: allow
        location: top

    - paloaltonetworks.panos.panos_security_rule:
        provider: "{{ device }}"
        rule_name: "{{ item.rule_name }}"
        description: "{{ item.description | default('') }}"
        source_zone: "{{ item.source_zone }}"
        source_ip: "{{ item.source_ip }}"
        destination_zone: "{{ item.destination_zone }}"
        destination_ip: "{{ item.destination_ip }}"
        application: "{{ item.application }}"
        action: "{{ item.rule_action }}"
        location: "{{ item.location }}"
        existing_rule: "{{ item.existing_rule }}"
      loop: "{{ policies }}"

    - paloaltonetworks.panos.panos_commit_firewall:
        provider: '{{ device }}'
