---
- hosts: all
  connection: local
  vars:
    device:
      ip_address: "{{ panos_url }}"
      username: "{{ panos_user }}"
      password: "{{ panos_password }}"

  tasks:

    - name: Gather facts for device
      paloaltonetworks.panos.panos_facts:
        provider: '{{ device }}'

    - name: Display model, PAN-OS version
      ansible.builtin.debug:
        msg: "Model: {{ ansible_facts['net_model'] }}, version: {{ ansible_facts['net_version'] }}"
