---
- hosts: all
  connection: local

  vars:
    device:
      ip_address: "{{ panos_url }}"
      username: "{{ panos_user }}"
      password: "{{ panos_password }}"

  tasks:
    - paloaltonetworks.panos.panos_zone:
        provider: '{{ device }}'
        zone: 'Untrust'
        mode: 'layer3'

    - paloaltonetworks.panos.panos_zone:
        provider: '{{ device }}'
        zone: 'Trust'
        mode: 'layer3'

    - paloaltonetworks.panos.panos_security_rule:
        provider: '{{ device }}'
        rule_name: 'SSH permit'
        description: 'SSH rule test'
        source_zone: ['Untrust']
        source_ip: ['any']
        destination_zone: ['Trust']
        destination_ip: ['any']
        application: ['ssh']
        action: 'allow'

    - paloaltonetworks.panos.panos_security_rule:
        provider: '{{ device }}'
        rule_name: 'SSH permit 2'
        description: 'SSH rule test'
        source_zone: ['Untrust']
        source_ip: ['10.10.10.0/24']
        destination_zone: ['Trust']
        destination_ip:
          - 172.16.10.0/24
          - 192.168.1.0/24
        application: ['ssh']
        action: 'allow'

#    - paloaltonetworks.panos.panos_commit_firewall:
#        provider: '{{ device }}'
